const DAYS=[
{date:'JUL 10',day:'FRI',title:'Arrival & yakiniku',route:'Narita → Nippori',routeText:'Keisei Skyliner to Nippori · ~36 min · reserved seat.',stops:[
 {time:'15:05',tag:'ARRIVE',name:'Narita Airport Terminal 2',note:'Land on JX802. Immigration, bags, then follow Keisei signs.',place:'Narita Airport Terminal 2'},
 {time:'16:20',tag:'TRANSFER',name:'Keisei Skyliner → Nippori',note:'Buy or collect a reserved-seat ticket. Keep your IC card for city trains.',place:'Keisei Skyliner Narita Airport Terminal 2'},
 {time:'17:15',tag:'CHECK-IN',name:'ART HOTEL Nippori Lungwood',note:'One minute from Nippori Station. Reset, shower, and head out around 18:10.',place:'ART HOTEL Nippori Lungwood'},
 {time:'19:00',tag:'RESERVED · TABELOG',name:'一頭牛焼肉 房家',note:'Your booked yakiniku dinner. Confirm the exact branch in the Tabelog reservation.',place:'一頭牛焼肉 房家 東京'}]},
{date:'JUL 11',day:'SAT',title:'Shibuya shopping',route:'Nippori → Shibuya',routeText:'JR Yamanote Line direct · ~33 min. Start at Harajuku side, finish Dōgenzaka.',stops:[
 {time:'09:15',tag:'SAVED · SHRINE',name:'Meiji Shrine',note:'Start at the quiet northern end of the route before the shops open. Allow about one hour.',place:'Meiji Jingu'},
 {time:'10:45',tag:'SHOP · STREETWEAR',name:'ballaholic TOKYO',note:'Basketball apparel and Tokyo-exclusive streetwear. Walk south toward Shibuya.',place:'ballaholic TOKYO'},
 {time:'12:00',tag:'SHOP · SHOES',name:'Onitsuka Tiger Shibuya 1',note:'Try sizes before lunch; carry your passport for tax-free eligibility.',place:'Onitsuka Tiger Shibuya 1'},
 {time:'13:15',tag:'LUNCH',name:'AFURI Shibuya Dōgenzaka',note:'Yuzu shio ramen is the classic. Expect a short weekend queue.',place:'AFURI Shibuya Dogenzaka'},
 {time:'14:30',tag:'SHOP · RUNNING',name:'adidas Brand Center Shibuya',note:'Compare running models and Japan pricing. Log prices in the checklist below.',place:'adidas Brand Center Shibuya'},
 {time:'16:15',tag:'SAVED · COFFEE',name:'Fuglen Tokyo',note:'Your saved Tomigaya coffee stop. A good reset before dinner; Hachiko and Miyashita Park remain easy walk-by extras.',place:'Fuglen Tokyo'},
 {time:'18:00',tag:'DINNER PICK',name:'挽肉と米 Shibuya',note:'Excellent hamburger rice set, but slots can be competitive. Backup: Uobei Shibuya Dogenzaka.',place:'挽肉と米 渋谷'}]},
{date:'JUL 12',day:'SUN',title:'Shinjuku sport edit',route:'Nippori → Shinjuku',routeText:'JR Yamanote Line direct · ~22 min. Most stops cluster around the East Exit.',stops:[
 {time:'10:00',tag:'COFFEE',name:'Blue Bottle Shinjuku',note:'Open Sundays from 08:00. A calm start inside NEWoMan before the shops.',place:'Blue Bottle Coffee Shinjuku'},
 {time:'11:00',tag:'SHOP · GOLF',name:'Victoria Golf Shinjuku',note:'Your main shopping stop for clubs, apparel, shoes, and accessories. Carry your passport and compare tax-free pricing.',place:'Victoria Golf Shinjuku'},
 {time:'13:30',tag:'LUNCH · CHOOSE ONE',name:'Lunch options',note:'Pick by mood and queue length. Tap a choice to preview it on the map.',place:'Tsujihan Kagurazaka',options:[{name:'Tsujihan · seafood bowl',place:'Tsujihan Kagurazaka'},{name:'Fūunji · tsukemen',place:'Fuunji Shinjuku'},{name:'Udon Shin · handmade udon',place:'Udon Shin Shinjuku'}]},
 {time:'18:00',tag:'DINNER · CHOOSE ONE',name:'Dinner options',note:'Sushi no Midori is the first choice; the alternatives keep the evening flexible if the queue is long.',place:'Sushi no Midori Shinjuku',options:[{name:'Sushi no Midori · sushi',place:'Sushi no Midori Shinjuku'},{name:'Tsukada Farm · saved izakaya',place:'塚田農場 新宿東口駅前店'},{name:'Numazuko · conveyor sushi',place:'Numazuko Shinjuku'},{name:'Tsunahachi · tempura',place:'Shinjuku Tsunahachi Souhonten'}]}]},
{date:'JUL 13',day:'MON',title:'Shinbashi → Asakusa',route:'Nippori → Shinbashi → Asakusa',routeText:'Yamanote to Shinbashi; Ginza Line onward to Asakusa. IC card throughout.',stops:[
 {time:'12:00',tag:'LUNCH · COLLEAGUES',name:'Yamaya Shinbashi',note:'Meet colleagues for mentaiko-focused set lunch. Confirm the branch in your group chat.',place:'Yamaya Shinbashi Tokyo'},
 {time:'14:15',tag:'LANDMARK',name:'Kaminarimon & Sensō-ji',note:'Enter via Thunder Gate and browse Nakamise before coffee.',place:'Kaminarimon Gate'},
 {time:'15:30',tag:'COFFEE',name:'FUGLEN ASAKUSA',note:'Norwegian coffee by Sensō-ji; open Monday until 21:00.',place:'FUGLEN ASAKUSA'},
 {time:'16:10',tag:'SHOW',name:'Asakusa Rockza',note:'Suggested second show, 16:10–18:00. Adult entry listed at ¥10,000; verify the July program.',place:'Asakusa Rockza'},
 {time:'18:20',tag:'SAVED · MARKET',name:'Ameyoko Shopping District',note:'Browse the lively market street on the way toward your saved Ueno ramen dinner.',place:'Ameyoko Shopping District'},
 {time:'19:15',tag:'DINNER',name:'牛骨ラーメン 磯川 上野店',note:'Head toward Ueno for beef-bone ramen, then one Yamanote stop home.',place:'牛骨ラーメン 磯川 上野店'}]},
{date:'JUL 14',day:'TUE',title:'Mt. Fuji day tour',route:'Hotel pickup · no transfer',routeText:'Your Klook tour collects you directly from ART HOTEL Nippori Lungwood. Be in the lobby 10–15 minutes early.',stops:[
 {time:'06:30',tag:'EARLY START',name:'Breakfast & weather check',note:'Pack water, a light rain layer, sunscreen, and a warmer layer for elevation.',place:'ART HOTEL Nippori Lungwood'},
 {time:'07:15',tag:'MEET IN LOBBY',name:'ART HOTEL Nippori Lungwood',note:'Wait in the hotel lobby 10–15 minutes before the confirmed Klook pickup time.',place:'ART HOTEL Nippori Lungwood'},
 {time:'07:30',tag:'BOOKED · KLOOK',name:'Mt. Fuji day tour pickup',note:'Hotel pickup confirmed—no morning rail transfer required. Keep the booking voucher ready.',place:'ART HOTEL Nippori Lungwood'},
 {time:'12:00',tag:'DAY TOUR',name:'Mt. Fuji area',note:'The operator controls the route. Visibility changes quickly; keep the schedule flexible.',place:'Mount Fuji Japan'},
 {time:'19:30',tag:'EASY EVENING',name:'Return & casual dinner',note:'Stay near Nippori: try neighborhood soba or an izakaya based on your return time.',place:'Nippori Station'}]},
{date:'JUL 15',day:'WED',title:'Yanaka & departure',route:'Nippori → NRT Terminal 2',routeText:'Skyliner direct · leave Nippori around 16:45 for a relaxed airport arrival.',stops:[
 {time:'10:00',tag:'CHECK-OUT',name:'Leave bags at the hotel',note:'Check out and ask reception to hold luggage until late afternoon.',place:'ART HOTEL Nippori Lungwood'},
 {time:'10:30',tag:'NEIGHBORHOOD',name:'Yanaka Ginza',note:'A low-stress final morning: old-Tokyo lanes, snacks, ceramics, and small gifts.',place:'Yanaka Ginza'},
 {time:'12:30',tag:'LUNCH PICK',name:'HAGISO / HAGI CAFE',note:'Coffee and light lunch in a converted wooden apartment near Yanaka Cemetery.',place:'HAGI CAFE Tokyo'},
 {time:'15:30',tag:'FINAL CHECK',name:'Hotel luggage pickup',note:'Passport, purchases, wallet, charger. Walk to Keisei Nippori.',place:'ART HOTEL Nippori Lungwood'},
 {time:'16:45',tag:'AIRPORT TRANSFER',name:'Skyliner to Narita T2',note:'Target airport arrival around 17:30, over three hours before departure.',place:'Keisei Nippori Station'},
 {time:'20:40',tag:'FLIGHT',name:'JX805 · NRT → TPE',note:'Scheduled arrival in Taipei at 23:20. Terminal 2 at Narita.',place:'Narita Airport Terminal 2'}]}
];
const weatherCodes={0:['Clear','☀'],1:['Mostly clear','🌤'],2:['Partly cloudy','⛅'],3:['Cloudy','☁'],45:['Foggy','☁'],48:['Foggy','☁'],51:['Light drizzle','🌦'],53:['Drizzle','🌦'],55:['Heavy drizzle','🌧'],61:['Light rain','🌦'],63:['Rain','🌧'],65:['Heavy rain','🌧'],80:['Rain showers','🌦'],81:['Rain showers','🌧'],82:['Heavy showers','⛈'],95:['Thunderstorms','⛈'],96:['Storms','⛈'],99:['Storms','⛈']};
const DEFAULT_STOPS=DAYS.map(day=>JSON.parse(JSON.stringify(day.stops)));
const storedSchedules=JSON.parse(localStorage.getItem('tokyo-custom-schedules')||'null');
if(Array.isArray(storedSchedules))storedSchedules.forEach((stops,i)=>{if(Array.isArray(stops)&&DAYS[i])DAYS[i].stops=stops});
let selectedDay=0,forecast={},items=JSON.parse(localStorage.getItem('tokyo-shopping')||'null')||[
 {name:'Running shoes',store:'Shibuya stores',price:18000,done:false},{name:'Japanese denim',store:'Shibuya',price:22000,done:false},{name:'Golf accessories',store:'Victoria Golf Shinjuku',price:12000,done:false},{name:'Tokyo-only souvenir',store:'Open choice',price:5000,done:false}
];
items=items.map(item=>item.name==='Running shoes'&&/Alpen/i.test(item.store)?{...item,store:'Shibuya stores'}:item.name==='Golf accessories'&&/Golf5|Alpen/i.test(item.store)?{...item,store:'Victoria Golf Shinjuku'}:item);
const $=s=>document.querySelector(s), yen=n=>new Intl.NumberFormat('ja-JP').format(n||0);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function renderTabs(){ $('#dayTabs').innerHTML=DAYS.map((d,i)=>`<button class="day-tab ${i===selectedDay?'active':''}" data-day="${i}"><small>${d.day}</small><b>${d.date}</b></button>`).join('');document.querySelectorAll('.day-tab').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderDay()}) }
function mapUrl(place){return `https://www.google.com/maps?q=${encodeURIComponent(place)}&output=embed`}
function renderDay(){renderTabs();const d=DAYS[selectedDay];$('#timeline').innerHTML=`<div class="schedule-tools"><div><p class="eyebrow">${d.day} · ${d.date}</p><h3>${esc(d.title)}</h3></div><div class="schedule-actions"><button class="reset-schedule" type="button">還原當日</button><button class="add-schedule" type="button">＋ 新增行程</button></div></div>`+d.stops.map((s,i)=>`<div class="timeline-item ${i===0?'active':''}" data-stop="${i}"><time>${esc(s.time)}</time><div class="timeline-rail"></div><div class="timeline-content"><small>${esc(s.tag)}</small><h3>${esc(s.name)}</h3><p>${esc(s.note)}</p>${s.options?`<div class="choice-list">${s.options.map((o,j)=>`<button class="choice-btn ${j===0?'selected':''}" data-choice-stop="${i}" data-choice="${j}">${esc(o.name)}</button>`).join('')}</div>`:''}<div class="timeline-actions"><button type="button" class="edit-stop" data-edit-stop="${i}">編輯</button><button type="button" class="delete-stop" data-delete-stop="${i}">刪除</button></div></div></div>`).join('');$('#routeTitle').textContent=d.route;$('#routeText').textContent=d.routeText;if(d.stops.length)selectStop(0);else{$('#mapPlace').textContent='尚未安排行程';$('#mapFrame').removeAttribute('src')}document.querySelectorAll('.timeline-item').forEach(el=>el.onclick=()=>selectStop(+el.dataset.stop));document.querySelectorAll('.choice-btn').forEach(el=>el.onclick=e=>{e.stopPropagation();selectChoice(+el.dataset.choiceStop,+el.dataset.choice,el)});document.querySelector('.add-schedule').onclick=()=>openScheduleSheet();document.querySelector('.reset-schedule').onclick=resetCurrentDay;document.querySelectorAll('[data-edit-stop]').forEach(button=>button.onclick=e=>{e.stopPropagation();openScheduleSheet(+button.dataset.editStop)});document.querySelectorAll('[data-delete-stop]').forEach(button=>button.onclick=e=>{e.stopPropagation();deleteScheduleStop(+button.dataset.deleteStop)});updateDayWeather()}
function selectStop(i){const d=DAYS[selectedDay],s=d.stops[i];document.querySelectorAll('.timeline-item').forEach((x,j)=>x.classList.toggle('active',j===i));$('#mapFrame').src=mapUrl(s.place);$('#mapPlace').textContent=s.name;const origin=i?d.stops[i-1].place:'ART HOTEL Nippori Lungwood';$('#routeLink').href=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(s.place)}&travelmode=transit`}
function selectChoice(stopIndex,choiceIndex,button){const d=DAYS[selectedDay],s=d.stops[stopIndex],choice=s.options[choiceIndex];document.querySelectorAll('.timeline-item').forEach((x,j)=>x.classList.toggle('active',j===stopIndex));button.parentElement.querySelectorAll('.choice-btn').forEach(x=>x.classList.toggle('selected',x===button));$('#mapFrame').src=mapUrl(choice.place);$('#mapPlace').textContent=choice.name;const origin=stopIndex?d.stops[stopIndex-1].place:'ART HOTEL Nippori Lungwood';$('#routeLink').href=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(choice.place)}&travelmode=transit`}
function persistSchedules(){localStorage.setItem('tokyo-custom-schedules',JSON.stringify(DAYS.map(day=>day.stops)))}
function openScheduleSheet(index=null){const editing=Number.isInteger(index),stop=editing?DAYS[selectedDay].stops[index]:null;$('#scheduleEditIndex').value=editing?index:'';$('#scheduleSheetTitle').textContent=editing?'修改行程':'新增行程';$('#sheetDayLabel').textContent=`${DAYS[selectedDay].day} · ${DAYS[selectedDay].date}`;$('#scheduleTime').value=stop?.time||'12:00';$('#scheduleTag').value=['景點','餐廳','購物','咖啡','交通','預約','自由行程'].includes(stop?.tag)?stop.tag:'自由行程';$('#scheduleName').value=stop?.name||'';$('#schedulePlace').value=stop?.place||'';$('#scheduleNote').value=stop?.note||'';$('#scheduleBackdrop').classList.add('open');$('#scheduleSheet').classList.add('open');document.body.classList.add('sheet-open');setTimeout(()=>$('#scheduleName').focus(),320)}
function closeScheduleSheet(){$('#scheduleBackdrop').classList.remove('open');$('#scheduleSheet').classList.remove('open');document.body.classList.remove('sheet-open')}
function deleteScheduleStop(index){const stop=DAYS[selectedDay].stops[index];if(!stop||!confirm(`刪除「${stop.name}」？`))return;DAYS[selectedDay].stops.splice(index,1);persistSchedules();renderDay();showToast('行程已刪除')}
function resetCurrentDay(){if(!confirm(`還原 ${DAYS[selectedDay].date} 的原始行程？你當天的自訂異動會被清除。`))return;DAYS[selectedDay].stops=JSON.parse(JSON.stringify(DEFAULT_STOPS[selectedDay]));persistSchedules();renderDay();showToast('已還原當日行程')}
$('#scheduleForm').onsubmit=event=>{event.preventDefault();const index=$('#scheduleEditIndex').value===''?null:+$('#scheduleEditIndex').value;const stop={time:$('#scheduleTime').value,tag:$('#scheduleTag').value,name:$('#scheduleName').value.trim(),place:$('#schedulePlace').value.trim()||$('#scheduleName').value.trim(),note:$('#scheduleNote').value.trim()||'自訂行程'};if(!stop.name)return;if(index===null)DAYS[selectedDay].stops.push(stop);else DAYS[selectedDay].stops[index]={...DAYS[selectedDay].stops[index],...stop};DAYS[selectedDay].stops.sort((a,b)=>a.time.localeCompare(b.time));persistSchedules();closeScheduleSheet();renderDay();showToast(index===null?'行程已新增':'行程已更新')};
$('#closeScheduleSheet').onclick=closeScheduleSheet;$('#cancelSchedule').onclick=closeScheduleSheet;$('#scheduleBackdrop').onclick=closeScheduleSheet;document.addEventListener('keydown',event=>{if(event.key==='Escape')closeScheduleSheet()});
document.querySelectorAll('[data-saved-place]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-saved-place]').forEach(x=>x.classList.toggle('active',x===button));const place=button.dataset.savedPlace;$('#mapFrame').src=mapUrl(place);$('#mapPlace').textContent=button.textContent;$('#routeLink').href=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent('ART HOTEL Nippori Lungwood')}&destination=${encodeURIComponent(place)}&travelmode=transit`;$('.route-map').classList.remove('saved-flash');requestAnimationFrame(()=>$('.route-map').classList.add('saved-flash'));$('.route-panel').scrollIntoView({behavior:'smooth',block:'center'})});
async function getWeather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=35.6762&longitude=139.6503&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&current=temperature_2m,weather_code&timezone=Asia%2FTokyo&forecast_days=16');if(!r.ok)throw 0;const x=await r.json();x.daily.time.forEach((t,i)=>forecast[t]={code:x.daily.weather_code[i],hi:Math.round(x.daily.temperature_2m_max[i]),lo:Math.round(x.daily.temperature_2m_min[i]),rain:x.daily.precipitation_probability_max[i]});const [desc,icon]=weatherCodes[x.current.weather_code]||['Mixed conditions','⛅'];$('#weatherTemp').textContent=Math.round(x.current.temperature_2m)+'°';$('#weatherText').textContent=desc+' · updated live';$('#weatherIcon').textContent=icon;$('#weatherAdvice').textContent=x.current.temperature_2m>29?'Tokyo is hot and humid—carry water and take indoor breaks.':'Comfortable for exploring; keep a light layer handy.';updateDayWeather()}catch(e){$('#weatherText').textContent='Forecast unavailable';$('#weatherAdvice').textContent='Open the dashboard with internet access to sync weather.'}}
function updateDayWeather(){const iso=`2026-07-${String(10+selectedDay).padStart(2,'0')}`,w=forecast[iso];if(!w){$('#dayWeather').textContent='Awaiting forecast';$('#dayAdvice').textContent='The live 16-day forecast will appear when available.';return}const [desc,icon]=weatherCodes[w.code]||['Mixed','⛅'];$('#dayWeather').textContent=`${icon} ${w.lo}–${w.hi}° · ${desc}`;$('#dayAdvice').textContent=w.rain>=50?`${w.rain}% rain chance. Carry a compact umbrella and prioritize indoor stops during showers.`:w.hi>=30?`Only ${w.rain}% rain, but expect heat. Water, sunscreen, and slower mid-afternoon pacing.`:`${w.rain}% rain chance. Good conditions for the planned route.`}
function saveItems(){localStorage.setItem('tokyo-shopping',JSON.stringify(items));renderShopping()}
function renderShopping(){const done=items.filter(x=>x.done).length;$('#checkProgress').textContent=`${done} of ${items.length} found`;$('#shoppingList').innerHTML=items.map((x,i)=>`<div class="shop-item ${x.done?'done':''}"><input type="checkbox" ${x.done?'checked':''} data-check="${i}" aria-label="Mark ${x.name} found"><div><div class="item-name">${x.name}</div><div class="item-store">${x.store}</div></div><input class="price-input" type="number" value="${x.price||''}" data-price="${i}" aria-label="Price in yen"><span class="twd">≈ NT$${yen(Math.round((x.price||0)*.205))}</span><button class="delete" data-delete="${i}" aria-label="Delete">×</button></div>`).join('');document.querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>{items[+e.dataset.check].done=e.checked;saveItems()});document.querySelectorAll('[data-price]').forEach(e=>e.onchange=()=>{items[+e.dataset.price].price=+e.value;saveItems()});document.querySelectorAll('[data-delete]').forEach(e=>e.onclick=()=>{items.splice(+e.dataset.delete,1);saveItems()})}
$('#addItem').onclick=()=>{$('#newItemName').focus();$('#addItemForm').scrollIntoView({behavior:'smooth',block:'center'})};
$('#addItemForm').onsubmit=e=>{e.preventDefault();const name=$('#newItemName').value.trim(),store=$('#newItemStore').value.trim()||'Open choice',price=+$('#newItemPrice').value||0;if(!name)return;items.push({name,store,price,done:false});saveItems();e.target.reset();showToast(`${name} added to your list.`)};
function clocks(){const now=new Date();$('#tokyoClock').textContent='Tokyo · '+new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'}).format(now);const dep=new Date('2026-07-10T10:40:00+08:00'),ms=dep-now;if(ms>0){const days=Math.floor(ms/864e5),hours=Math.floor(ms%864e5/36e5);$('#tripCountdown').textContent=`${days}D ${hours}H`}else{$('#tripCountdown').textContent='IN TOKYO';$('#countdownLabel').textContent='The adventure is underway'}}
$('#notifyBtn').onclick=async()=>{if(!('Notification'in window)){showToast('Browser notifications are not supported here.');return}const p=await Notification.requestPermission();if(p==='granted'){localStorage.setItem('tokyo-notify','yes');$('#notifyStatus').textContent='Reminders enabled for this browser.';new Notification('Tokyo reminders enabled',{body:'We’ll flag check-in and departure milestones while the dashboard is open.'})}else showToast('Notification permission was not granted.')};
function reminderCheck(){if(localStorage.getItem('tokyo-notify')!=='yes'||Notification.permission!=='granted')return;const now=Date.now(),events=[['Leave for Narita soon','Pick up your bags and leave Nippori by 16:45.','2026-07-15T16:00:00+09:00'],['Airport check-in','JX805 departs Terminal 2 at 20:40.','2026-07-15T17:30:00+09:00'],['Boarding soon','Head to your gate and check the airport screens.','2026-07-15T19:50:00+09:00']];events.forEach(([title,body,time],i)=>{const key='reminder-'+i;if(now>=new Date(time).getTime()&&now-new Date(time).getTime()<3600000&&!sessionStorage.getItem(key)){new Notification(title,{body});sessionStorage.setItem(key,'1')}})}
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView());renderDay();renderShopping();getWeather();clocks();setInterval(clocks,30000);setInterval(reminderCheck,60000);reminderCheck();
